# Generated by Django 5.2.2 on 2026-04-11 03:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('patta_name', models.CharField(max_length=255)),
                ('primary_phone', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid 10-digit mobile number.', regex='^[6-9]\\d{9}$')])),
                ('secondary_phone', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid 10-digit mobile number.', regex='^[6-9]\\d{9}$')])),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('address_line3', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Pincode must be 6 digits.', regex='^\\d{6}$')])),
                ('native_place', models.CharField(choices=[('Nerkuppai', 'Nerkuppai'), ('Vendanpatti', 'Vendanpatti')], max_length=20)),
            ],
            options={
                'ordering': ['member_id'],
            },
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_1', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid 10-digit mobile number.', regex='^[6-9]\\d{9}$')])),
                ('phone_2', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid 10-digit mobile number.', regex='^[6-9]\\d{9}$')])),
                ('type', models.CharField(choices=[('Guest', 'Guest'), ('Penn Vitarr', 'Penn Vitarr')], max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_no', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid 10-digit mobile number.', regex='^[6-9]\\d{9}$')])),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='memberships.member')),
            ],
            options={
                'ordering': ['receipt_no'],
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date', models.DateField()),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='memberships.receipt')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EelamEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('Member', 'Member'), ('Non-Member', 'Non-Member')], max_length=20)),
                ('phone', models.CharField(editable=False, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid 10-digit mobile number.', regex='^[6-9]\\d{9}$')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eelam_entries', to='memberships.member')),
                ('relative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eelam_entries', to='memberships.relative')),
            ],
            options={
                'verbose_name': 'Eelam Entry',
                'verbose_name_plural': 'Eelam Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction2026',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(editable=False, max_length=255)),
                ('phone', models.CharField(editable=False, max_length=10)),
                ('donation_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('unpaid_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='memberships.member')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='memberships.receipt')),
            ],
            options={
                'verbose_name': 'Transaction 2026',
                'verbose_name_plural': 'Transactions 2026',
                'ordering': ['-created_at'],
            },
        ),
    ]
