# Generated by Django 5.2.2 on 2026-04-12 10:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_auctionitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(editable=False, max_length=255)),
                ('primary_phone_number', models.CharField(editable=False, max_length=10)),
                ('native_place', models.CharField(choices=[('Nerkuppai', 'Nerkuppai'), ('Vendanpatti', 'Vendanpatti')], editable=False, max_length=20)),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=20)),
                ('challan', models.CharField(blank=True, max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auction_transactions', to='memberships.auctionitem')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auction_transactions', to='memberships.member')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auction_transactions', to='memberships.receipt')),
            ],
            options={
                'verbose_name': 'Auction Transaction',
                'verbose_name_plural': 'Auction Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Transaction2026',
        ),
    ]
