# Generated by Django 5.2.2 on 2026-04-12 16:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_auctiontransaction_delete_transaction2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctiontransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'AuctionTransaction', 'verbose_name_plural': 'Auction_Transactions'},
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor_type', models.CharField(choices=[('Member', 'Member'), ('Non-Member', 'Non-Member')], max_length=20)),
                ('donor_name', models.CharField(editable=False, max_length=255)),
                ('phone', models.CharField(editable=False, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid 10-digit mobile number.', regex='^[6-9]\\d{9}$')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='memberships.member')),
                ('relative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='memberships.relative')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
