# Generated by Django 5.2.2 on 2026-04-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_auctionitem_auction_item_name_tamil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='price',
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='auction_item_name_tamil',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
