# Generated by Django 5.2.2 on 2026-05-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0011_auctionitemtoken_auction_item_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitemtoken',
            name='id',
        ),
        migrations.AlterField(
            model_name='auctionitemtoken',
            name='token_number',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
