# Generated by Django 5.2.2 on 2026-05-22 17:02

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0015_split_registration_and_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_status', models.CharField(choices=[('All', 'All'), ('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=20)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('summary', models.JSONField(default=dict)),
                ('payment_status_breakdown', models.JSONField(blank=True, default=list)),
                ('transactions', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'auction_report',
                'ordering': ['-generated_at', '-id'],
            },
        ),
    ]
