# Generated by Django 5.2.2 on 2026-05-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0020_receipt_relative_member_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctiontransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Auction_Transaction', 'verbose_name_plural': 'Auction_Transactions'},
        ),
    ]
