# Generated by Django 5.2.2 on 2026-05-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0021_alter_auctiontransaction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relative',
            name='type',
            field=models.CharField(choices=[('Guest', 'Guest'), ('Penn Veetaar', 'Penn Veetaar')], max_length=20),
        ),
        migrations.RunSQL(
            sql="UPDATE memberships_relative SET type = 'Penn Veetaar' WHERE type = 'Penn Vitarr';",
            reverse_sql="UPDATE memberships_relative SET type = 'Penn Vitarr' WHERE type = 'Penn Veetaar';",
        ),
    ]
