# Generated by Django 5.2.2 on 2026-05-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0021_alter_auctiontransaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='relative',
            name='place',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
