# Generated by Django 5.2.2 on 2026-05-25 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0022_rename_penn_vitarr_to_penn_veetaar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid 10-digit mobile number.', regex='^[6-9]\\d{9}$')]),
        ),
    ]
