# Generated by Django 5.2.2 on 2026-07-05 16:06

import memberships.models
from django.db import migrations, models


def year_from(value, fallback):
    source = value or fallback
    return source.year if source else memberships.models.current_record_year()


def backfill_record_year(apps, schema_editor):
    date_sources = {
        "Member": lambda row: year_from(None, row.created_at),
        "Relative": lambda row: year_from(None, row.created_at),
        "AuctionItem": lambda row: year_from(None, row.created_at),
        "EelamEntry": lambda row: year_from(None, row.created_at),
        "Donation": lambda row: year_from(None, row.created_at),
        "Receipt": lambda row: year_from(row.receipt_date, row.created_at),
        "Deposit": lambda row: year_from(row.date, row.created_at),
        "AuctionReport": lambda row: year_from(row.generated_at, row.created_at),
    }

    for model_name, get_year in date_sources.items():
        model = apps.get_model("memberships", model_name)
        rows = list(model.objects.all())
        for row in rows:
            row.record_year = get_year(row)
        if rows:
            model.objects.bulk_update(rows, ["record_year"])

    AuctionTransaction = apps.get_model("memberships", "AuctionTransaction")
    transactions = list(AuctionTransaction.objects.select_related("receipt").all())
    for transaction in transactions:
        receipt_date = transaction.receipt.receipt_date if transaction.receipt_id and transaction.receipt else None
        transaction.record_year = year_from(receipt_date, transaction.created_at)
    if transactions:
        AuctionTransaction.objects.bulk_update(transactions, ["record_year"])


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0022_relative_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='record_year',
            field=models.PositiveIntegerField(default=memberships.models.current_record_year),
        ),
        migrations.AddField(
            model_name='auctionreport',
            name='record_year',
            field=models.PositiveIntegerField(default=memberships.models.current_record_year),
        ),
        migrations.AddField(
            model_name='auctiontransaction',
            name='record_year',
            field=models.PositiveIntegerField(default=memberships.models.current_record_year),
        ),
        migrations.AddField(
            model_name='deposit',
            name='record_year',
            field=models.PositiveIntegerField(default=memberships.models.current_record_year),
        ),
        migrations.AddField(
            model_name='donation',
            name='record_year',
            field=models.PositiveIntegerField(default=memberships.models.current_record_year),
        ),
        migrations.AddField(
            model_name='eelamentry',
            name='record_year',
            field=models.PositiveIntegerField(default=memberships.models.current_record_year),
        ),
        migrations.AddField(
            model_name='member',
            name='record_year',
            field=models.PositiveIntegerField(default=memberships.models.current_record_year),
        ),
        migrations.AddField(
            model_name='receipt',
            name='record_year',
            field=models.PositiveIntegerField(default=memberships.models.current_record_year),
        ),
        migrations.AddField(
            model_name='relative',
            name='record_year',
            field=models.PositiveIntegerField(default=memberships.models.current_record_year),
        ),
        migrations.RunPython(backfill_record_year, migrations.RunPython.noop),
    ]
