# Generated by Django 5.2.2 on 2026-07-06 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0023_auctionitem_record_year_auctionreport_record_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('notification_type', models.CharField(choices=[('PAYMENT_SUCCESS', 'Payment Success')], max_length=40)),
                ('message', models.TextField()),
                ('meta_message_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('response_json', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('auction_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='memberships.auctiontransaction')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
