# Generated by Django 5.2.2 on 2026-05-25 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0023_remove_secondary_phone_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relative',
            name='phone_2',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid 10-digit mobile number.', regex='^[6-9]\\d{9}$')]),
        ),
    ]
