# Generated by Django 5.2.2 on 2026-08-03 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0024_notificationlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='record_year',
        ),
        migrations.RemoveField(
            model_name='relative',
            name='record_year',
        ),
    ]
