# Generated by Django 5.2.2 on 2026-08-15 11:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import memberships.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0025_remove_member_record_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_no', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('invoice_date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('Issued', 'Issued'), ('Cancelled', 'Cancelled')], default='Issued', max_length=20)),
                ('record_year', models.PositiveIntegerField(default=memberships.models.current_record_year)),
                ('auction_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='memberships.auctiontransaction')),
            ],
            options={
                'ordering': ['-created_at', '-invoice_no'],
            },
        ),
    ]
