# Generated by Django 5.2.2 on 2026-05-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0026_rename_vendhanpatti_to_venthanpatti'),
    ]

    operations = [
        migrations.AddField(
            model_name='relative',
            name='native_place',
            field=models.CharField(blank=True, choices=[('Nerkuppai', 'Nerkuppai'), ('Venthanpatti', 'Venthanpatti')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='auctiontransaction',
            name='native_place',
            field=models.CharField(blank=True, choices=[('Nerkuppai', 'Nerkuppai'), ('Venthanpatti', 'Venthanpatti')], editable=False, max_length=20),
        ),
    ]
