# Generated by Django 5.2.2 on 2026-05-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0027_add_native_place_to_relative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relative',
            name='native_place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
